// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Copyright field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copyright: prismic.RichTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → Links*
 */
export interface HeaderDocumentDataLinksItem {
  /**
   * page field in *Header → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[].page
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  page: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Links field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<HeaderDocumentDataLinksItem>>;

  /**
   * Button field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | WelcomeSlice
  | BecomeAMemberSlice
  | HpFormSlice
  | HpBandaSlice
  | HpPeopleSlice
  | HpOurProjectsSlice
  | HpJoinUsSlice
  | HpAboutSlice
  | RichTextSlice;

/**
 * Content for Homepage documents
 */
interface PageDocumentData {
  /**
   * seo title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seo_title: prismic.KeyTextField;

  /**
   * seo description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FooterDocument | HeaderDocument | PageDocument;

/**
 * Item in *BecomeAMember → Default → Primary → BaseMember*
 */
export interface BecomeAMemberSliceDefaultPrimaryBasememberItem {
  /**
   * Icon field in *BecomeAMember → Default → Primary → BaseMember*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.basemember[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Description field in *BecomeAMember → Default → Primary → BaseMember*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.basemember[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *BecomeAMember → Default → Primary → Believer*
 */
export interface BecomeAMemberSliceDefaultPrimaryBelieverItem {
  /**
   * Icon field in *BecomeAMember → Default → Primary → Believer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.believer[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Description field in *BecomeAMember → Default → Primary → Believer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.believer[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *BecomeAMember → Default → Primary*
 */
export interface BecomeAMemberSliceDefaultPrimary {
  /**
   * AboveTitle field in *BecomeAMember → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.abovetitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  abovetitle: prismic.RichTextField;

  /**
   * Title field in *BecomeAMember → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * MemberTitle field in *BecomeAMember → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.membertitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  membertitle: prismic.RichTextField;

  /**
   * BaseMember field in *BecomeAMember → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.basemember[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  basemember: prismic.GroupField<
    Simplify<BecomeAMemberSliceDefaultPrimaryBasememberItem>
  >;

  /**
   * BeaLiverTitle field in *BecomeAMember → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.bealivertitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bealivertitle: prismic.RichTextField;

  /**
   * bealiver under title field in *BecomeAMember → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.bealiver_under_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bealiver_under_title: prismic.RichTextField;

  /**
   * Believer field in *BecomeAMember → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.believer[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  believer: prismic.GroupField<
    Simplify<BecomeAMemberSliceDefaultPrimaryBelieverItem>
  >;

  /**
   * Join us field in *BecomeAMember → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: become_a_member.default.primary.join_us
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  join_us: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for BecomeAMember Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BecomeAMemberSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BecomeAMemberSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BecomeAMember*
 */
type BecomeAMemberSliceVariation = BecomeAMemberSliceDefault;

/**
 * BecomeAMember Shared Slice
 *
 * - **API ID**: `become_a_member`
 * - **Description**: BecomeAMember
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BecomeAMemberSlice = prismic.SharedSlice<
  "become_a_member",
  BecomeAMemberSliceVariation
>;

/**
 * Primary content in *HpWhoWeAre → Default → Primary*
 */
export interface HpAboutSliceDefaultPrimary {
  /**
   * above title field in *HpWhoWeAre → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_about.default.primary.above_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  above_title: prismic.RichTextField;

  /**
   * title field in *HpWhoWeAre → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * CardTitle field in *HpWhoWeAre → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_about.default.primary.cardtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cardtitle: prismic.RichTextField;

  /**
   * description field in *HpWhoWeAre → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_about.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * button field in *HpWhoWeAre → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_about.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * below card title field in *HpWhoWeAre → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_about.default.primary.below_card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  below_card_title: prismic.RichTextField;

  /**
   * below card button field in *HpWhoWeAre → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_about.default.primary.below_card_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  below_card_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image field in *HpWhoWeAre → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_about.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HpWhoWeAre Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HpAboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HpWhoWeAre*
 */
type HpAboutSliceVariation = HpAboutSliceDefault;

/**
 * HpWhoWeAre Shared Slice
 *
 * - **API ID**: `hp_about`
 * - **Description**: HpAbout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpAboutSlice = prismic.SharedSlice<
  "hp_about",
  HpAboutSliceVariation
>;

/**
 * Item in *HpNumbers → Default → Primary → Field*
 */
export interface HpBandaSliceDefaultPrimaryFieldItem {
  /**
   * number field in *HpNumbers → Default → Primary → Field*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_banda.default.primary.field[].number
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  number: prismic.RichTextField;

  /**
   * description field in *HpNumbers → Default → Primary → Field*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_banda.default.primary.field[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *HpNumbers → Default → Primary*
 */
export interface HpBandaSliceDefaultPrimary {
  /**
   * Field field in *HpNumbers → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_banda.default.primary.field[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  field: prismic.GroupField<Simplify<HpBandaSliceDefaultPrimaryFieldItem>>;
}

/**
 * Default variation for HpNumbers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpBandaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HpBandaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HpNumbers*
 */
type HpBandaSliceVariation = HpBandaSliceDefault;

/**
 * HpNumbers Shared Slice
 *
 * - **API ID**: `hp_banda`
 * - **Description**: HpBanda
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpBandaSlice = prismic.SharedSlice<
  "hp_banda",
  HpBandaSliceVariation
>;

/**
 * Item in *HpForm → Default → Primary → informations*
 */
export interface HpFormSliceDefaultPrimaryInformationsItem {
  /**
   * info icon field in *HpForm → Default → Primary → informations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.informations[].info_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  info_icon: prismic.ImageField<never>;

  /**
   * info text field in *HpForm → Default → Primary → informations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.informations[].info_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  info_text: prismic.RichTextField;
}

/**
 * Item in *HpForm → Default → Primary → social images*
 */
export interface HpFormSliceDefaultPrimarySocialImagesItem {
  /**
   * image field in *HpForm → Default → Primary → social images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.social_images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * social link field in *HpForm → Default → Primary → social images*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.social_images[].social_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *HpForm → Default → Primary*
 */
export interface HpFormSliceDefaultPrimary {
  /**
   * abovetitle field in *HpForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.abovetitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  abovetitle: prismic.RichTextField;

  /**
   * title field in *HpForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * form title field in *HpForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  form_title: prismic.RichTextField;

  /**
   * about title field in *HpForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.about_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  about_title: prismic.RichTextField;

  /**
   * informations field in *HpForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.informations[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  informations: prismic.GroupField<
    Simplify<HpFormSliceDefaultPrimaryInformationsItem>
  >;

  /**
   * social images field in *HpForm → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_form.default.primary.social_images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_images: prismic.GroupField<
    Simplify<HpFormSliceDefaultPrimarySocialImagesItem>
  >;
}

/**
 * Default variation for HpForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HpFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HpForm*
 */
type HpFormSliceVariation = HpFormSliceDefault;

/**
 * HpForm Shared Slice
 *
 * - **API ID**: `hp_form`
 * - **Description**: HpForm
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpFormSlice = prismic.SharedSlice<"hp_form", HpFormSliceVariation>;

/**
 * Item in *HpOurTeams → Default → Primary → Cards*
 */
export interface HpJoinUsSliceDefaultPrimaryCardsItem {
  /**
   * Image field in *HpOurTeams → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_join_us.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *HpOurTeams → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_join_us.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *HpOurTeams → Default → Primary*
 */
export interface HpJoinUsSliceDefaultPrimary {
  /**
   * AboveTitle field in *HpOurTeams → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_join_us.default.primary.abovetitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  abovetitle: prismic.RichTextField;

  /**
   * Title field in *HpOurTeams → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_join_us.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Cards field in *HpOurTeams → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_join_us.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<HpJoinUsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for HpOurTeams Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpJoinUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HpJoinUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HpOurTeams*
 */
type HpJoinUsSliceVariation = HpJoinUsSliceDefault;

/**
 * HpOurTeams Shared Slice
 *
 * - **API ID**: `hp_join_us`
 * - **Description**: HpJoinUs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpJoinUsSlice = prismic.SharedSlice<
  "hp_join_us",
  HpJoinUsSliceVariation
>;

/**
 * Item in *HpOurProjects → Default → Primary → Cards*
 */
export interface HpOurProjectsSliceDefaultPrimaryCardsItem {
  /**
   * Image field in *HpOurProjects → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *HpOurProjects → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.cards[].category
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  category: prismic.RichTextField;

  /**
   * Title field in *HpOurProjects → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *HpOurProjects → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Competenze field in *HpOurProjects → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.cards[].competenze
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  competenze: prismic.RichTextField;

  /**
   * TecnologyImg field in *HpOurProjects → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.cards[].tecnologyimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tecnologyimg: prismic.ImageField<never>;
}

/**
 * Primary content in *HpOurProjects → Default → Primary*
 */
export interface HpOurProjectsSliceDefaultPrimary {
  /**
   * AboveTitle field in *HpOurProjects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.abovetitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  abovetitle: prismic.RichTextField;

  /**
   * Title field in *HpOurProjects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Cards field in *HpOurProjects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<HpOurProjectsSliceDefaultPrimaryCardsItem>
  >;

  /**
   * button projects field in *HpOurProjects → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.button_projects
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_projects: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button projects arrow field in *HpOurProjects → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_our_projects.default.primary.button_projects_arrow
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  button_projects_arrow: prismic.ImageField<never>;
}

/**
 * Default variation for HpOurProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpOurProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HpOurProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HpOurProjects*
 */
type HpOurProjectsSliceVariation = HpOurProjectsSliceDefault;

/**
 * HpOurProjects Shared Slice
 *
 * - **API ID**: `hp_our_projects`
 * - **Description**: HpOurProjects
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpOurProjectsSlice = prismic.SharedSlice<
  "hp_our_projects",
  HpOurProjectsSliceVariation
>;

/**
 * Item in *HpOurPeople → Default → Primary → Person*
 */
export interface HpPeopleSliceDefaultPrimaryPersonItem {
  /**
   * Name field in *HpOurPeople → Default → Primary → Person*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_people.default.primary.person[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * title field in *HpOurPeople → Default → Primary → Person*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_people.default.primary.person[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *HpOurPeople → Default → Primary → Person*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_people.default.primary.person[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * person image field in *HpOurPeople → Default → Primary → Person*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_people.default.primary.person[].person_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  person_image: prismic.ImageField<never>;
}

/**
 * Primary content in *HpOurPeople → Default → Primary*
 */
export interface HpPeopleSliceDefaultPrimary {
  /**
   * above title field in *HpOurPeople → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_people.default.primary.above_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  above_title: prismic.RichTextField;

  /**
   * title field in *HpOurPeople → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_people.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Person field in *HpOurPeople → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hp_people.default.primary.person[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  person: prismic.GroupField<Simplify<HpPeopleSliceDefaultPrimaryPersonItem>>;
}

/**
 * Default variation for HpOurPeople Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpPeopleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HpPeopleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HpOurPeople*
 */
type HpPeopleSliceVariation = HpPeopleSliceDefault;

/**
 * HpOurPeople Shared Slice
 *
 * - **API ID**: `hp_people`
 * - **Description**: HpPeople
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HpPeopleSlice = prismic.SharedSlice<
  "hp_people",
  HpPeopleSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *HpWelcome → Default → Primary*
 */
export interface WelcomeSliceDefaultPrimary {
  /**
   * above title field in *HpWelcome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.above_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  above_title: prismic.RichTextField;

  /**
   * Title field in *HpWelcome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * under title field in *HpWelcome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.under_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  under_title: prismic.RichTextField;

  /**
   * image field in *HpWelcome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * find out more field in *HpWelcome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.find_out_more
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  find_out_more: prismic.RichTextField;

  /**
   * find out more arrow field in *HpWelcome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.find_out_more_arrow
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  find_out_more_arrow: prismic.ImageField<never>;
}

/**
 * Default variation for HpWelcome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WelcomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WelcomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HpWelcome*
 */
type WelcomeSliceVariation = WelcomeSliceDefault;

/**
 * HpWelcome Shared Slice
 *
 * - **API ID**: `welcome`
 * - **Description**: Welcome
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WelcomeSlice = prismic.SharedSlice<
  "welcome",
  WelcomeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BecomeAMemberSlice,
      BecomeAMemberSliceDefaultPrimaryBasememberItem,
      BecomeAMemberSliceDefaultPrimaryBelieverItem,
      BecomeAMemberSliceDefaultPrimary,
      BecomeAMemberSliceVariation,
      BecomeAMemberSliceDefault,
      HpAboutSlice,
      HpAboutSliceDefaultPrimary,
      HpAboutSliceVariation,
      HpAboutSliceDefault,
      HpBandaSlice,
      HpBandaSliceDefaultPrimaryFieldItem,
      HpBandaSliceDefaultPrimary,
      HpBandaSliceVariation,
      HpBandaSliceDefault,
      HpFormSlice,
      HpFormSliceDefaultPrimaryInformationsItem,
      HpFormSliceDefaultPrimarySocialImagesItem,
      HpFormSliceDefaultPrimary,
      HpFormSliceVariation,
      HpFormSliceDefault,
      HpJoinUsSlice,
      HpJoinUsSliceDefaultPrimaryCardsItem,
      HpJoinUsSliceDefaultPrimary,
      HpJoinUsSliceVariation,
      HpJoinUsSliceDefault,
      HpOurProjectsSlice,
      HpOurProjectsSliceDefaultPrimaryCardsItem,
      HpOurProjectsSliceDefaultPrimary,
      HpOurProjectsSliceVariation,
      HpOurProjectsSliceDefault,
      HpPeopleSlice,
      HpPeopleSliceDefaultPrimaryPersonItem,
      HpPeopleSliceDefaultPrimary,
      HpPeopleSliceVariation,
      HpPeopleSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      WelcomeSlice,
      WelcomeSliceDefaultPrimary,
      WelcomeSliceVariation,
      WelcomeSliceDefault,
    };
  }
}
