// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  become_a_member: dynamic(() => import("./BecomeAMember")),
  hp_about: dynamic(() => import("./HpWhoWeAre")),
  hp_banda: dynamic(() => import("./HpNumbers")),
  hp_form: dynamic(() => import("./HpForm")),
  hp_join_us: dynamic(() => import("./HpOurTeams")),
  hp_our_projects: dynamic(() => import("./HpOurProjects")),
  hp_people: dynamic(() => import("./HpOurPeople")),
  rich_text: dynamic(() => import("./RichText")),
  welcome: dynamic(() => import("./HpWelcome")),
};
